/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JPanel;
import views.view_dashboard;
import views.view_dataauditor;
import views.view_datakriteria;
import views.view_hasilrangking;
import views.view_laporan;
import views.view_pengaturan;
import views.view_perbandinganalternatif;
import views.view_perbandingankriteria;
import views.view_prosesahp;


/**
 *
 * @author USER
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form mani
     */
    public Main() {
        initComponents();
    }

    public void setColor(JPanel p) {
        p.setBackground(new Color(33, 48, 66));
    }

    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(52, 73, 94));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSidebar = new javax.swing.JPanel();
        sb_dashboard = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        sb_dataauditor = new javax.swing.JPanel();
        dataauditor = new javax.swing.JLabel();
        sb_datakriteria = new javax.swing.JPanel();
        datakriteria = new javax.swing.JLabel();
        sb_perbandingankrtieria = new javax.swing.JPanel();
        perbandingankriteria = new javax.swing.JLabel();
        sb_perbandinganalternatif = new javax.swing.JPanel();
        perbandinganalternatif = new javax.swing.JLabel();
        sb_prosesahp = new javax.swing.JPanel();
        prosesahp = new javax.swing.JLabel();
        sb_hasilrangking = new javax.swing.JPanel();
        hasilrangking = new javax.swing.JLabel();
        sb_laporan = new javax.swing.JPanel();
        laporan = new javax.swing.JLabel();
        sb_pengaturan = new javax.swing.JPanel();
        pengaturan = new javax.swing.JLabel();
        lmasterdata1 = new javax.swing.JLabel();
        lpenentuanahp1 = new javax.swing.JLabel();
        lhasil1 = new javax.swing.JLabel();
        llainnya1 = new javax.swing.JLabel();
        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnContent = new javax.swing.JPanel();
        pnDasar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnSidebar.setBackground(new java.awt.Color(52, 73, 94));

        sb_dashboard.setBackground(new java.awt.Color(52, 73, 94));
        sb_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sb_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sb_dashboardMouseExited(evt);
            }
        });

        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sb_dashboardLayout = new javax.swing.GroupLayout(sb_dashboard);
        sb_dashboard.setLayout(sb_dashboardLayout);
        sb_dashboardLayout.setHorizontalGroup(
            sb_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_dashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_dashboardLayout.setVerticalGroup(
            sb_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sb_dataauditor.setBackground(new java.awt.Color(52, 73, 94));

        dataauditor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dataauditor.setForeground(new java.awt.Color(255, 255, 255));
        dataauditor.setText("Data Auditor");
        dataauditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataauditorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataauditorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataauditorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_dataauditorLayout = new javax.swing.GroupLayout(sb_dataauditor);
        sb_dataauditor.setLayout(sb_dataauditorLayout);
        sb_dataauditorLayout.setHorizontalGroup(
            sb_dataauditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_dataauditorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(dataauditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_dataauditorLayout.setVerticalGroup(
            sb_dataauditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sb_dataauditorLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(dataauditor)
                .addContainerGap())
        );

        sb_datakriteria.setBackground(new java.awt.Color(52, 73, 94));

        datakriteria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datakriteria.setForeground(new java.awt.Color(255, 255, 255));
        datakriteria.setText("Data Kriteria");
        datakriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datakriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datakriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datakriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_datakriteriaLayout = new javax.swing.GroupLayout(sb_datakriteria);
        sb_datakriteria.setLayout(sb_datakriteriaLayout);
        sb_datakriteriaLayout.setHorizontalGroup(
            sb_datakriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_datakriteriaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(datakriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_datakriteriaLayout.setVerticalGroup(
            sb_datakriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_datakriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datakriteria)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sb_perbandingankrtieria.setBackground(new java.awt.Color(52, 73, 94));

        perbandingankriteria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        perbandingankriteria.setForeground(new java.awt.Color(255, 255, 255));
        perbandingankriteria.setText("Perbandingan Kriteria");
        perbandingankriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbandingankriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perbandingankriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perbandingankriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_perbandingankrtieriaLayout = new javax.swing.GroupLayout(sb_perbandingankrtieria);
        sb_perbandingankrtieria.setLayout(sb_perbandingankrtieriaLayout);
        sb_perbandingankrtieriaLayout.setHorizontalGroup(
            sb_perbandingankrtieriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_perbandingankrtieriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(perbandingankriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_perbandingankrtieriaLayout.setVerticalGroup(
            sb_perbandingankrtieriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sb_perbandingankrtieriaLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(perbandingankriteria)
                .addContainerGap())
        );

        sb_perbandinganalternatif.setBackground(new java.awt.Color(52, 73, 94));

        perbandinganalternatif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        perbandinganalternatif.setForeground(new java.awt.Color(255, 255, 255));
        perbandinganalternatif.setText("Perbandingan Alternatif");
        perbandinganalternatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbandinganalternatifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perbandinganalternatifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perbandinganalternatifMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_perbandinganalternatifLayout = new javax.swing.GroupLayout(sb_perbandinganalternatif);
        sb_perbandinganalternatif.setLayout(sb_perbandinganalternatifLayout);
        sb_perbandinganalternatifLayout.setHorizontalGroup(
            sb_perbandinganalternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_perbandinganalternatifLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(perbandinganalternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_perbandinganalternatifLayout.setVerticalGroup(
            sb_perbandinganalternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_perbandinganalternatifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perbandinganalternatif)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sb_prosesahp.setBackground(new java.awt.Color(52, 73, 94));

        prosesahp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prosesahp.setForeground(new java.awt.Color(255, 255, 255));
        prosesahp.setText("Proses AHP");
        prosesahp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prosesahpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prosesahpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prosesahpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_prosesahpLayout = new javax.swing.GroupLayout(sb_prosesahp);
        sb_prosesahp.setLayout(sb_prosesahpLayout);
        sb_prosesahpLayout.setHorizontalGroup(
            sb_prosesahpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_prosesahpLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(prosesahp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_prosesahpLayout.setVerticalGroup(
            sb_prosesahpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sb_prosesahpLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(prosesahp)
                .addContainerGap())
        );

        sb_hasilrangking.setBackground(new java.awt.Color(52, 73, 94));

        hasilrangking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hasilrangking.setForeground(new java.awt.Color(255, 255, 255));
        hasilrangking.setText("Hasil Rangking");
        hasilrangking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasilrangkingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hasilrangkingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hasilrangkingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_hasilrangkingLayout = new javax.swing.GroupLayout(sb_hasilrangking);
        sb_hasilrangking.setLayout(sb_hasilrangkingLayout);
        sb_hasilrangkingLayout.setHorizontalGroup(
            sb_hasilrangkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_hasilrangkingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(hasilrangking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_hasilrangkingLayout.setVerticalGroup(
            sb_hasilrangkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sb_hasilrangkingLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(hasilrangking)
                .addContainerGap())
        );

        sb_laporan.setBackground(new java.awt.Color(52, 73, 94));

        laporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_laporanLayout = new javax.swing.GroupLayout(sb_laporan);
        sb_laporan.setLayout(sb_laporanLayout);
        sb_laporanLayout.setHorizontalGroup(
            sb_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_laporanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_laporanLayout.setVerticalGroup(
            sb_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laporan)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sb_pengaturan.setBackground(new java.awt.Color(52, 73, 94));

        pengaturan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        pengaturan.setText("Pengaturan");
        pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengaturanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengaturanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengaturanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sb_pengaturanLayout = new javax.swing.GroupLayout(sb_pengaturan);
        sb_pengaturan.setLayout(sb_pengaturanLayout);
        sb_pengaturanLayout.setHorizontalGroup(
            sb_pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_pengaturanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sb_pengaturanLayout.setVerticalGroup(
            sb_pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sb_pengaturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengaturan)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lmasterdata1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lmasterdata1.setForeground(new java.awt.Color(153, 153, 153));
        lmasterdata1.setText("Master Data");

        lpenentuanahp1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lpenentuanahp1.setForeground(new java.awt.Color(153, 153, 153));
        lpenentuanahp1.setText("Penentuan AHP");

        lhasil1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lhasil1.setForeground(new java.awt.Color(153, 153, 153));
        lhasil1.setText("Hasil");

        llainnya1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        llainnya1.setForeground(new java.awt.Color(153, 153, 153));
        llainnya1.setText("Lainnya");

        javax.swing.GroupLayout pnSidebarLayout = new javax.swing.GroupLayout(pnSidebar);
        pnSidebar.setLayout(pnSidebarLayout);
        pnSidebarLayout.setHorizontalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sb_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_pengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnSidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lmasterdata1)
                    .addComponent(lpenentuanahp1)
                    .addComponent(lhasil1)
                    .addComponent(llainnya1))
                .addGap(0, 154, Short.MAX_VALUE))
            .addComponent(sb_laporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_hasilrangking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_prosesahp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_perbandinganalternatif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_perbandingankrtieria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_datakriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sb_dataauditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnSidebarLayout.setVerticalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSidebarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sb_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lmasterdata1)
                .addGap(25, 25, 25)
                .addComponent(sb_dataauditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sb_datakriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lpenentuanahp1)
                .addGap(16, 16, 16)
                .addComponent(sb_perbandingankrtieria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sb_perbandinganalternatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sb_prosesahp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lhasil1)
                .addGap(12, 12, 12)
                .addComponent(sb_hasilrangking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sb_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(llainnya1)
                .addGap(26, 26, 26)
                .addComponent(sb_pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pnHeader.setBackground(new java.awt.Color(33, 48, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SPK Penilaian Kinerja Auditor - Metode AHP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-verified-account-25.png"))); // NOI18N
        jLabel2.setText("user");

        btnLogout.setBackground(new java.awt.Color(52, 73, 94));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-shutdown-25.png"))); // NOI18N
        btnLogout.setText("Keluar");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addGap(30, 30, 30))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnLogout))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnContent.setBackground(new java.awt.Color(204, 204, 204));

        pnDasar.setBackground(new java.awt.Color(255, 255, 255));
        pnDasar.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pnDasar.removeAll();
        pnDasar.add(new view_dashboard());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void sb_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sb_dashboardMouseEntered
        setColor(sb_dashboard);
    }//GEN-LAST:event_sb_dashboardMouseEntered

    private void sb_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sb_dashboardMouseExited
        resetColor(sb_dashboard);
    }//GEN-LAST:event_sb_dashboardMouseExited

    private void dataauditorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataauditorMouseEntered
        setColor(sb_dataauditor);        // TODO add your handling code here:
    }//GEN-LAST:event_dataauditorMouseEntered

    private void dataauditorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataauditorMouseExited
        resetColor(sb_dataauditor);        // TODO add your handling code here:
    }//GEN-LAST:event_dataauditorMouseExited

    private void datakriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datakriteriaMouseEntered
        setColor(sb_datakriteria);        // TODO add your handling code here:
    }//GEN-LAST:event_datakriteriaMouseEntered

    private void datakriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datakriteriaMouseExited
        resetColor(sb_datakriteria);
    }//GEN-LAST:event_datakriteriaMouseExited

    private void perbandingankriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandingankriteriaMouseEntered
        setColor(sb_perbandingankrtieria);
    }//GEN-LAST:event_perbandingankriteriaMouseEntered

    private void perbandingankriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandingankriteriaMouseExited
        resetColor(sb_perbandingankrtieria);
    }//GEN-LAST:event_perbandingankriteriaMouseExited

    private void perbandinganalternatifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandinganalternatifMouseEntered
        setColor(sb_perbandinganalternatif);
    }//GEN-LAST:event_perbandinganalternatifMouseEntered

    private void perbandinganalternatifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandinganalternatifMouseExited
        resetColor(sb_perbandinganalternatif);
    }//GEN-LAST:event_perbandinganalternatifMouseExited

    private void prosesahpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesahpMouseEntered
        setColor(sb_prosesahp);
    }//GEN-LAST:event_prosesahpMouseEntered

    private void prosesahpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesahpMouseExited
        resetColor(sb_prosesahp);
    }//GEN-LAST:event_prosesahpMouseExited

    private void hasilrangkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasilrangkingMouseEntered
        setColor(sb_hasilrangking);
    }//GEN-LAST:event_hasilrangkingMouseEntered

    private void hasilrangkingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasilrangkingMouseExited
        resetColor(sb_hasilrangking);
    }//GEN-LAST:event_hasilrangkingMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        setColor(sb_laporan);
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        resetColor(sb_laporan);
    }//GEN-LAST:event_laporanMouseExited

    private void pengaturanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseEntered
        setColor(sb_pengaturan);
    }//GEN-LAST:event_pengaturanMouseEntered

    private void pengaturanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseExited
        resetColor(sb_pengaturan);
    }//GEN-LAST:event_pengaturanMouseExited

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_dashboard());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dataauditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataauditorMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_dataauditor());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_dataauditorMouseClicked

    private void datakriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datakriteriaMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_datakriteria());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_datakriteriaMouseClicked

    private void perbandingankriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandingankriteriaMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_perbandingankriteria());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_perbandingankriteriaMouseClicked

    private void perbandinganalternatifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbandinganalternatifMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_perbandinganalternatif());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_perbandinganalternatifMouseClicked

    private void prosesahpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesahpMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_prosesahp());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_prosesahpMouseClicked

    private void hasilrangkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasilrangkingMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_hasilrangking());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_hasilrangkingMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_laporan());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_laporanMouseClicked

    private void pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseClicked
        pnDasar.removeAll();
        pnDasar.add(new view_pengaturan());
        pnDasar.repaint();
        pnDasar.revalidate();
    }//GEN-LAST:event_pengaturanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dataauditor;
    private javax.swing.JLabel datakriteria;
    private javax.swing.JLabel hasilrangking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel lhasil1;
    private javax.swing.JLabel llainnya1;
    private javax.swing.JLabel lmasterdata1;
    private javax.swing.JLabel lpenentuanahp1;
    private javax.swing.JLabel pengaturan;
    private javax.swing.JLabel perbandinganalternatif;
    private javax.swing.JLabel perbandingankriteria;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnSidebar;
    private javax.swing.JLabel prosesahp;
    private javax.swing.JPanel sb_dashboard;
    private javax.swing.JPanel sb_dataauditor;
    private javax.swing.JPanel sb_datakriteria;
    private javax.swing.JPanel sb_hasilrangking;
    private javax.swing.JPanel sb_laporan;
    private javax.swing.JPanel sb_pengaturan;
    private javax.swing.JPanel sb_perbandinganalternatif;
    private javax.swing.JPanel sb_perbandingankrtieria;
    private javax.swing.JPanel sb_prosesahp;
    // End of variables declaration//GEN-END:variables

}
