/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;

import configs.KoneksiDB;
import dao.UserDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.Main;
import models.User;

/**
 *
 * @author ryumaaa
 */
public class auth_register extends javax.swing.JFrame {

    int x, y;
    private Connection conn;
    private Statement st;
    private ResultSet rslogin;
    private String sql = "";
    public static String nmlengkap;
    public static User userLogin;
    String username, password;

    /**
     * Creates new form formLogin
     */
    public static String getNamaLengkap() {
        return nmlengkap;
    }

    public void setColor(JPanel p) {
        p.setBackground(new Color(204, 0, 51));
    }

    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(153, 153, 153));
    }

    /**
     * Creates new form Login
     */
    public auth_register() {
        initComponents();
        lbl_hideeye.setVisible(false);
        lbl_register.requestFocus();
    }

    private void prosesRegister() {

        String username = tUsername.getText().trim();
        String password = new String(jPassword.getPassword()).trim();

        if (username.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Username tidak boleh kosong");

            return;
        }

        if (password.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Password tidak boleh kosong");

            return;
        }

        UserDAO dao = new UserDAO();

        if (dao.cekUsername(username)) {

            JOptionPane.showMessageDialog(this,
                    "Username sudah digunakan");

            return;
        }

        User user = new User();

        user.setUsername(username);
        user.setPassword(password);

        boolean berhasil = dao.register(user);

        if (berhasil) {

            JOptionPane.showMessageDialog(this,
                    "Registrasi berhasil");

            dispose();

            new auth_login().setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this,
                    "Registrasi gagal");

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Utama = new javax.swing.JPanel();
        lbl_hideeye = new javax.swing.JLabel();
        lbl_eye = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        pn_login = new javax.swing.JPanel();
        lbl_register = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        pn_cancel = new javax.swing.JPanel();
        lbl_cancel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pn_Utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_Utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_hideeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_hide_20px_1.png"))); // NOI18N
        lbl_hideeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_hideeyeMousePressed(evt);
            }
        });
        pn_Utama.add(lbl_hideeye, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        lbl_eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_eye_20px_1.png"))); // NOI18N
        lbl_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_eyeMousePressed(evt);
            }
        });
        pn_Utama.add(lbl_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_close_window_50px.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pn_Utama.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Account");
        pn_Utama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 370, -1));

        tUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tUsername.setText("Username");
        tUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUsernameFocusLost(evt);
            }
        });
        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });
        pn_Utama.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 370, 60));

        pn_login.setBackground(new java.awt.Color(153, 153, 153));

        lbl_register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_register.setForeground(new java.awt.Color(255, 255, 255));
        lbl_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register.setText("Register");
        lbl_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_registerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_loginLayout = new javax.swing.GroupLayout(pn_login);
        pn_login.setLayout(pn_loginLayout);
        pn_loginLayout.setHorizontalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_register, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        pn_loginLayout.setVerticalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_register, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pn_Utama.add(pn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 370, -1));

        jPassword.setText("********");
        jPassword.setPreferredSize(new java.awt.Dimension(54, 20));
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        pn_Utama.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 370, 60));

        pn_cancel.setBackground(new java.awt.Color(153, 153, 153));

        lbl_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_cancel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-back-25.png"))); // NOI18N
        lbl_cancel.setText("Back To Login Form");
        lbl_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_cancelLayout = new javax.swing.GroupLayout(pn_cancel);
        pn_cancel.setLayout(pn_cancelLayout);
        pn_cancelLayout.setHorizontalGroup(
            pn_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        pn_cancelLayout.setVerticalGroup(
            pn_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pn_Utama.add(pn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 370, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        pn_Utama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        pn_Utama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancelMouseExited
        resetColor(pn_cancel);
    }//GEN-LAST:event_lbl_cancelMouseExited

    private void lbl_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancelMouseEntered
        setColor(pn_cancel);
    }//GEN-LAST:event_lbl_cancelMouseEntered

    private void lbl_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cancelMouseClicked
        auth_login login = new auth_login();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lbl_cancelMouseClicked

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        String password = jPassword.getText();
        if (password.equals("") || password.equals("********")) {
            jPassword.setText("********");
        }
    }//GEN-LAST:event_jPasswordFocusLost

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        String password = jPassword.getText();
        if (password.equals("********")) {
            jPassword.setText("");
        }
    }//GEN-LAST:event_jPasswordFocusGained

    private void lbl_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseExited
        resetColor(pn_login);
    }//GEN-LAST:event_lbl_registerMouseExited

    private void lbl_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseEntered
        setColor(pn_login);
    }//GEN-LAST:event_lbl_registerMouseEntered

    private void lbl_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseClicked
        prosesRegister();
    }//GEN-LAST:event_lbl_registerMouseClicked

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void tUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusLost
        String username = tUsername.getText();
        if (username.equals("") || username.equals("Username")) {
            tUsername.setText("Username");
        }
    }//GEN-LAST:event_tUsernameFocusLost

    private void tUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusGained
        String username = tUsername.getText();
        if (username.equals("Username")) {
            tUsername.setText("");
        }
    }//GEN-LAST:event_tUsernameFocusGained

    private void lbl_hideeyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hideeyeMousePressed
        lbl_eye.setVisible(true);
        lbl_hideeye.setVisible(false);
        jPassword.setEchoChar('*');
    }//GEN-LAST:event_lbl_hideeyeMousePressed

    private void lbl_eyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eyeMousePressed
        lbl_eye.setVisible(false);
        lbl_hideeye.setVisible(true);
        jPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lbl_eyeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        int close = JOptionPane.showConfirmDialog(null, "Apakah ingin keluar dari aplikasi?", "pesan", JOptionPane.YES_NO_OPTION);
        if (close == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(auth_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(auth_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(auth_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(auth_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new auth_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lbl_cancel;
    private javax.swing.JLabel lbl_eye;
    private javax.swing.JLabel lbl_hideeye;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JPanel pn_Utama;
    private javax.swing.JPanel pn_cancel;
    private javax.swing.JPanel pn_login;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
